# Site settings
title: Blogging PsyKzz
author: Matt Smith <PsyKzz>
description: "Does things, does stuff."

# Page defaults
defaults:
  -
    scope:
      path: ""      # empty string for all files
      type: posts   # limit to posts
    values:
      is_post: true # automatically set is_post=true for all posts

# Other settings
permalink: pretty
exclude: [vendor, build, Gemfile, CNAME]
