# Site settings
title: PsyKzz Blogging
author: Matt Smith <PsyKzz>
description: "Does things, does stuff."

# Page defaults
defaults:
  -
    scope:
      path: ""      # empty string for all files
      type: posts   # limit to posts
    values:
      is_post: true # automatically set is_post=true for all posts

# Add sitemap
gems:
  - jekyll-sitemap
  - jekyll-seo-tag

# Other settings
permalink: pretty
exclude: [vendor, build, Gemfile, CNAME]
